edition = "2024"
max_width = 120
use_small_heuristics = "Max"
newline_style = "Unix"
hard_tabs = false
tab_spaces = 4

trailing_comma = "Vertical"
merge_derives = true
blank_lines_upper_bound = 1

reorder_imports = true
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

wrap_comments = true
comment_width = 100
format_code_in_doc_comments = true
normalize_doc_attributes = true

format_macro_bodies = true
